export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCCESS = 'REGISTER_SUCCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCCESS = 'LOGIN_SUCCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST';
export const GET_CURRENT_USER_SUCCCESS = 'GET_CURRENT_USER_SUCCCESS';
export const GET_CURRENT_USER_FAIL = 'GET_CURRENT_USER_FAIL';

export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_SUCCCESS = 'ORDER_SUCCCESS';
export const ORDER_FAIL = 'ORDER_FAIL';
