export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';

export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';

export const ORDER_CART = 'ORDER_CART';

export const DELETE_CART = 'DELETE_CART';

export const CHANGE_CART = 'CHANGE_CART';
